"""added is publish to news

Revision ID: 55297424981f
Revises: 
Create Date: 2022-03-07 21:00:14.890496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55297424981f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'is_published')
    # ### end Alembic commands ###
